# Generated by Django 3.2 on 2023-04-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_content_type_object_id',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='object_id',
        ),
        migrations.AddField(
            model_name='favorite',
            name='name',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='recipes.recipe', verbose_name='Название рецепта'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'user'), name='unique_user_content'),
        ),
    ]
